import './globals.css'
import type { Metadata } from 'next'
import { Inter, Outfit } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import NavBar from '@/components/NavBar'


const outfit = Outfit({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider publishableKey={"pk_test_c2F2ZWQtc3BhcnJvdy0yMy5jbGVyay5hY2NvdW50cy5kZXYk"}>
      <html lang="PT-br">
        <body className={outfit.className}>
          <NavBar/>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
